#!/usr/bin/env python3
"""Generate a complete, referentially-consistent e-commerce test dataset.

Model:  customers 1─* orders 1─* order_items *─1 products

Emits, into ./data:
  customers.csv, products.csv, orders.csv, order_items.csv   (flat, for inspection / file sources)
  seed.sql                                                    (INSERTs matching schema.sql)

Order totals are computed from their items, so the data satisfies the FK and the
total == sum(quantity*unit_price) invariant. Deterministic by default:

  python3 generate.py --customers 50 --products 30 --orders 200 --seed 42
"""

import argparse
import csv
import os
import random
from datetime import datetime, timedelta, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

FIRST = ["Avery", "Jordan", "Riley", "Morgan", "Casey", "Quinn", "Harper", "Rowan", "Sasha", "Devin", "Noa", "Kai"]
LAST = ["Nguyen", "Patel", "Garcia", "Smith", "Khan", "Okafor", "Rossi", "Larsson", "Mori", "Haddad", "Silva", "Cohen"]
COUNTRIES = ["US", "GB", "IN", "BR", "DE", "NG", "JP", "SE"]
CATEGORIES = ["Electronics", "Books", "Home", "Toys", "Apparel", "Grocery"]
ADJ = ["Compact", "Deluxe", "Eco", "Pro", "Mini", "Ultra", "Classic", "Smart"]
NOUN = ["Widget", "Gadget", "Lamp", "Mug", "Charger", "Notebook", "Bottle", "Speaker"]
STATUSES = ["PENDING", "PAID", "SHIPPED", "CANCELLED"]
EPOCH = datetime(2023, 1, 1, tzinfo=timezone.utc)


def iso(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S%z")


def gen_customers(n, rng):
    rows = []
    for i in range(1, n + 1):
        first, last = rng.choice(FIRST), rng.choice(LAST)
        rows.append({
            "id": i,
            "name": f"{first} {last}",
            "email": f"{first.lower()}.{last.lower()}{i}@example.com",
            "country": rng.choice(COUNTRIES),
            "created_at": iso(EPOCH + timedelta(days=rng.randint(0, 400), minutes=rng.randint(0, 1440))),
        })
    return rows


def gen_products(n, rng):
    rows = []
    for i in range(1, n + 1):
        rows.append({
            "id": i,
            "sku": f"SKU-{i:05d}",
            "name": f"{rng.choice(ADJ)} {rng.choice(NOUN)}",
            "category": rng.choice(CATEGORIES),
            "price": f"{rng.uniform(4.99, 499.99):.2f}",
            "in_stock": rng.random() > 0.15,
        })
    return rows


def gen_orders_and_items(n_orders, customers, products, rng):
    orders, items = [], []
    item_id = 0
    for oid in range(1, n_orders + 1):
        cust = rng.choice(customers)
        order_date = datetime.strptime(cust["created_at"], "%Y-%m-%d %H:%M:%S%z") + timedelta(
            days=rng.randint(0, 300), minutes=rng.randint(0, 1440)
        )
        n_items = rng.randint(1, 5)
        total = 0.0
        chosen = rng.sample(products, k=min(n_items, len(products)))
        for prod in chosen:
            item_id += 1
            qty = rng.randint(1, 4)
            unit_price = float(prod["price"])
            total += qty * unit_price
            items.append({
                "id": item_id,
                "order_id": oid,
                "product_id": prod["id"],
                "quantity": qty,
                "unit_price": f"{unit_price:.2f}",
            })
        orders.append({
            "id": oid,
            "customer_id": cust["id"],
            "status": rng.choice(STATUSES),
            "order_date": iso(order_date),
            "total": f"{total:.2f}",
        })
    return orders, items


def write_csv(name, rows):
    path = os.path.join(DATA, f"{name}.csv")
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    return path


def sql_value(v):
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def write_seed_sql(tables: dict):
    path = os.path.join(DATA, "seed.sql")
    with open(path, "w") as fh:
        fh.write("-- Generated by generate.py. Load after schema.sql.\nBEGIN;\n")
        for table, rows in tables.items():
            cols = list(rows[0].keys())
            for r in rows:
                vals = ", ".join(sql_value(r[c]) for c in cols)
                fh.write(f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({vals});\n")
        fh.write("COMMIT;\n")
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--customers", type=int, default=50)
    ap.add_argument("--products", type=int, default=30)
    ap.add_argument("--orders", type=int, default=200)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    os.makedirs(DATA, exist_ok=True)
    rng = random.Random(args.seed)

    customers = gen_customers(args.customers, rng)
    products = gen_products(args.products, rng)
    orders, items = gen_orders_and_items(args.orders, customers, products, rng)

    for name, rows in [("customers", customers), ("products", products),
                       ("orders", orders), ("order_items", items)]:
        write_csv(name, rows)
    write_seed_sql({"customers": customers, "products": products,
                    "orders": orders, "order_items": items})

    # Integrity sanity check: every order total equals the sum of its items.
    by_order = {}
    for it in items:
        by_order.setdefault(it["order_id"], 0.0)
        by_order[it["order_id"]] += it["quantity"] * float(it["unit_price"])
    mismatches = sum(1 for o in orders if abs(by_order.get(o["id"], 0.0) - float(o["total"])) > 0.01)

    print(f"customers={len(customers)} products={len(products)} "
          f"orders={len(orders)} order_items={len(items)}")
    print(f"total-vs-items mismatches: {mismatches} (expect 0)")
    print(f"wrote CSVs + seed.sql to {DATA}")


if __name__ == "__main__":
    main()
