#!/usr/bin/env python3
# Generate deterministic test data for the seatunnel-operator demo.
#
# Emits:
#   users.json                         -- the raw dataset (for inspection / reuse)
#   ../examples/testdata-to-console.yaml -- a SeaTunnelJob whose FakeSource is
#                                          seeded with these exact rows and prints
#                                          them to the console, so the operator
#                                          runs a real pipeline over known data.
#
# Deterministic by default (fixed seed) so the fixtures are reproducible:
#   python3 generate_test_data.py --rows 8 --seed 42
"""Test-data generator for the SeaTunnel operator demo pipeline."""

import argparse
import json
import os
import random

FIRST = ["Avery", "Jordan", "Riley", "Morgan", "Casey", "Quinn", "Harper", "Rowan", "Sasha", "Devin"]
LAST = ["Nguyen", "Patel", "Garcia", "Smith", "Khan", "Okafor", "Rossi", "Larsson", "Mori", "Haddad"]
COUNTRIES = ["US", "GB", "IN", "BR", "DE", "NG", "JP", "SE"]

HERE = os.path.dirname(os.path.abspath(__file__))
FIELDS = [("id", "bigint"), ("name", "string"), ("age", "int"), ("country", "string")]


def generate(n: int, rng: random.Random) -> list[dict]:
    rows = []
    for i in range(1, n + 1):
        rows.append(
            {
                "id": i,
                "name": f"{rng.choice(FIRST)} {rng.choice(LAST)}",
                "age": rng.randint(18, 72),
                "country": rng.choice(COUNTRIES),
            }
        )
    return rows


def hocon_rows(rows: list[dict]) -> str:
    """Render the rows as a SeaTunnel FakeSource `rows = [...]` block (HOCON)."""
    lines = []
    for r in rows:
        fields = f'[{r["id"]}, "{r["name"]}", {r["age"]}, "{r["country"]}"]'
        lines.append(f"        {{ kind = INSERT, fields = {fields} }}")
    return "\n".join(lines)


def schema_block() -> str:
    inner = ", ".join(f"{name} = {typ}" for name, typ in FIELDS)
    return f"schema = {{ fields {{ {inner} }} }}"


def render_job_yaml(rows: list[dict]) -> str:
    return f"""# GENERATED by testdata/generate_test_data.py -- do not edit by hand.
# A SeaTunnelJob that streams {len(rows)} known test records through SeaTunnel and
# prints them to the console. Apply it and watch the operator reconcile it:
#   kubectl apply -f testdata-to-console.yaml
#   kubectl get seatunneljobs -n seatunnel
#   kubectl logs -n seatunnel job/$(kubectl get stj testdata-to-console -n seatunnel -o jsonpath='{{.status.jobName}}')
apiVersion: marketplace.openautonomyx.io/v1alpha1
kind: SeaTunnelJob
metadata:
  name: testdata-to-console
  namespace: seatunnel
spec:
  image: apache/seatunnel:2.3.11
  engine: local
  config: |
    env {{
      parallelism = 1
      job.mode = "BATCH"
    }}
    source {{
      FakeSource {{
        {schema_block()}
        rows = [
{hocon_rows(rows)}
        ]
      }}
    }}
    sink {{
      Console {{}}
    }}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--rows", type=int, default=8)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", default=HERE, help="directory for users.json")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    rows = generate(args.rows, rng)

    json_path = os.path.join(args.out, "users.json")
    with open(json_path, "w") as fh:
        json.dump(rows, fh, indent=2)
        fh.write("\n")

    yaml_path = os.path.join(HERE, "..", "examples", "testdata-to-console.yaml")
    with open(yaml_path, "w") as fh:
        fh.write(render_job_yaml(rows))

    print(f"wrote {json_path} ({len(rows)} rows)")
    print(f"wrote {os.path.normpath(yaml_path)}")


if __name__ == "__main__":
    main()
